version: "3"
services:
  # heartbeats-function:
  #   image: my-docker-repo/presence-heartbeats-java:1.0-SNAPSHOT
  #   ports:
  #     - "8080:8080"
  # userstate-function:
  #   image: docker.io/library/presence-user-state-scala:HEAD-20211205-0612
  #   ports:
  #     - "8081:8080"
  # querying-function:
  #   build: presence-querying-python
  #   ports:
  #     - "8082:8080"
  akka-serverless-proxy-user-state:
    image: gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.3
    #command: -Dconfig.resource=dev-mode.conf -Dakkaserverless.proxy.eventing.support=google-pubsub-emulator
    command: -Dconfig.resource=dev-mode.conf -Dakkaserverless.proxy.eventing.support=kafka
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8080}
      #PUBSUB_EMULATOR_HOST: gcloud-pubsub-emulator
      BROKER_CONFIG_FILE: /conf/kafka.properties
    volumes:
      - ./conf:/conf
    depends_on: 
      - redpanda
  akka-serverless-proxy-heartbeats:
    image: gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.3
    #command: -Dconfig.resource=dev-mode.conf -Dakkaserverless.proxy.eventing.support=google-pubsub-emulator
    command: -Dconfig.resource=dev-mode.conf -Dakkaserverless.proxy.eventing.support=kafka
    ports:
      - "9001:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8081}
      #PUBSUB_EMULATOR_HOST: gcloud-pubsub-emulator
      BROKER_CONFIG_FILE: /conf/kafka.properties
    volumes:
      - ./conf:/conf
    depends_on: 
      - redpanda
  akka-serverless-proxy-querying:
    image: gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.3
    #command: -Dconfig.resource=dev-mode.conf -Dakkaserverless.proxy.eventing.support=google-pubsub-emulator
    command: -Dconfig.resource=dev-mode.conf -Dakkaserverless.proxy.eventing.support=kafka
    ports:
      - "9002:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8082}
      #PUBSUB_EMULATOR_HOST: gcloud-pubsub-emulator
      BROKER_CONFIG_FILE: /conf/kafka.properties
    volumes:
      - ./conf:/conf
    depends_on: 
      - redpanda
  # gcloud-pubsub-emulator:
  #   image: gcr.io/google.com/cloudsdktool/cloud-sdk:341.0.0
  #   command: gcloud beta emulators pubsub start --project=test --host-port=0.0.0.0:8085
  #   ports:
  #     - 8085:8085
  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    # NOTE: Please use the latest version here!
    image: docker.vectorized.io/vectorized/redpanda:v21.9.5
    container_name: redpanda-1
    ports:
      - 9092:9092
      - 29092:29092
